name = "RedStop Hugo"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Extension of Themefisher Restaurant"
homepage = "https://gethugothemes.com/products/restaurant/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'business', 'agency-template', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages']
features = ['bootstrap','responsive']
min_version = "0.62.0"

[author]
  name = "OpenJack"
  homepage = "https://OpenJack.com/"